import React from "react";
import { motion, useAnimation, useInView } from "framer-motion";
import { useRef, useEffect } from "react";
import { Command, RotateCcw, LayoutDashboard, ShieldAlert, Slash, Globe } from "lucide-react";

const features = [
  {
    icon: <RotateCcw size={26} />,
    title: "Proactive blocklist tracking",
    desc: (
      <>
        Be the first to know if your domain is added to a <a href="https://www.dnsbl.info/" target="_blank" rel="noopener noreferrer" className="underline">DNSBLs</a> such as those offered by <a href="https://www.spamhaus.org/" target="_blank" rel="noopener noreferrer" className="underline">Spamhaus</a> with removal requests generated by Resend.
      </>
    ),
  },
  {
    icon: <Command size={26} />,
    title: "Faster Time to Inbox",
    desc: "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions.",
  },
  {
    icon: <ShieldAlert size={26} />,
    title: "Build confidence with BIMI",
    desc: (
      <>
        Showcase your logo and company branding with <a href="https://bimi.agari.com/" target="_blank" rel="noopener noreferrer" className="underline">BIMI</a>. Receive guidance to obtain a <a href="https://en.wikipedia.org/wiki/Brand_Indicators_for_Message_Identification" target="_blank" rel="noopener noreferrer" className="underline">VMC</a> - the email equivalent of a checkmark on social media.
      </>
    ),
  },
  {
    icon: <LayoutDashboard size={26} />,
    title: "Managed Dedicated IPs",
    desc: "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.",
  },
  {
    icon: <Slash size={26} />,
    title: "Dynamic suppression list",
    desc: (
      <>
        Prevent repeated sending to recipients who no longer want your email and comply with standards like the <a href="https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business" target="_blank" rel="noopener noreferrer" className="underline">CAN-SPAM Act</a> and others.
      </>
    ),
  },
  {
    icon: <Globe size={26} />,
    title: "IP and domain monitoring",
    desc: "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.",
  },
];

const Features = () => {
  const ref = useRef(null);
  const inView = useInView(ref, { threshold: 0.15 });
  const controls = useAnimation();

  useEffect(() => {
    if (inView) controls.start("visible");
  }, [inView, controls]);

  const fadeUp = {
    hidden: { opacity: 0, y: 40 },
    visible: (i) => ({
      opacity: 1,
      y: 0,
      transition: { duration: 0.75, delay: i * 0.2, ease: "easeOut" },
    }),
  };

  return (
    <section ref={ref} className="relative w-full py-24 md:py-32 bg-black text-white overflow-hidden">
      <motion.div
        initial={{ opacity: 0, y: 40 }}
        animate={inView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.8 }}
        className="max-w-6xl mx-auto px-6 md:px-12 relative z-10"
      >
        <h2 className="text-4xl md:text-5xl font-semibold mb-14 leading-snug max-w-md text-white">
          <span className="text-white">Reach humans,</span> <span className="text-gray-400">not spam folders</span>
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-y-12 gap-x-16">
          {features.map((item, i) => (
            <motion.div
              key={i}
              variants={fadeUp}
              initial="hidden"
              animate={controls}
              custom={i}
              className="flex flex-col items-start space-y-3 max-w-sm"
            >
              <div className="text-gray-400 mb-2">
                {item.icon}
              </div>
              <h3 className="text-lg font-medium text-white">
                {item.title}
              </h3>
              <p className="text-gray-400 text-sm leading-relaxed">
                {item.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </section>
  );
};

export default Features;
