// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbcsmkmtteabatakmhlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiY3Nta210dGVhYmF0YWttaGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTMyNTgsImV4cCI6MjA2OTM4OTI1OH0.uEiJF9Fwo7iy-IEOROQ7L-CISMRLbjBA5ZCIFoUjlL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});